version: '3.1'
services:
  phone_contacts_db:
    image: postgres
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: phone_contacts_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: