server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587

network-address: http://localhost:8080